[project]
name = "test-redis-cache-module"
version = "0"
requires-python = ">=3.12"

dependencies = [
    "ipdb>=0.13.13",
    "locust>=2.32.7",
    "matplotlib>=3.10.1",
    "memory-profiler>=0.61.0",
    "redis>=5.2.1",
    "sentry-sdk",
]

[tool.uv.sources]
sentry-sdk = { path = "../../sentry-python", editable = true }
